{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
#    "metadata": {
#     "scrolled": true
#    },
   "outputs": [],
   "source": [
    "# dependencies BeautifulSoup, Pandas, and Requests/Splinter\n",
    "from bs4 import BeautifulSoup as bs\n",
    "from selenium import webdriver\n",
    "import pymongo\n",
    "import pandas as pd\n",
    "import requests\n",
    "from splinter import Browser\n",
    "from webdriver_manager.chrome import ChromeDriverManager"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "====== WebDriver manager ======\n",
      "Current google-chrome version is 92.0.4515\n",
      "Get LATEST driver version for 92.0.4515\n",
      "Get LATEST driver version for 92.0.4515\n",
      "Trying to download new driver from https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_win32.zip\n",
      "Driver has been saved in cache [C:\\Users\\jjel0\\.wdm\\drivers\\chromedriver\\win32\\92.0.4515.107]\n"
     ]
    }
   ],
   "source": [
    "# Setup splinter\n",
    "executable_path = {'executable_path': ChromeDriverManager().install()}\n",
    "browser = Browser('chrome', **executable_path, headless=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### NASA Mars News"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Scrape the [Mars News Site](https://redplanetscience.com/) and collect the latest News Title and Paragraph Text.\n",
    "    # Assign the text to variables that you can reference later.\n",
    "url_mars_news = 'https://redplanetscience.com/'\n",
    "browser.visit(url_mars_news)\n",
    "html_mars_news = browser.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<html>\n",
      " <head>\n",
      "  <meta charset=\"utf-8\"/>\n",
      "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\"/>\n",
      "  <link crossorigin=\"anonymous\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\" integrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\" rel=\"stylesheet\"/>\n",
      "  <link href=\"css/font.css\" rel=\"stylesheet\" type=\"text/css\"/>\n",
      "  <link href=\"css/app.css\" rel=\"stylesheet\" type=\"text/css\"/>\n",
      "  <link crossorigin=\"anonymous\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" rel=\"stylesheet\"/>\n",
      "  <title>\n",
      "   News - Mars Exploration Program\n",
      "  </title>\n",
      " </head>\n",
      " <body>\n",
      "  <div class=\"col-md-12\">\n",
      "   <div class=\"row\">\n",
      "    <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\">\n",
      "     <div class=\"container-fluid\">\n",
      "      <a class=\"navbar-brand\" href=\"#\">\n",
      "       <img src=\"image/nasa.png\" width=\"80\"/>\n",
      "       <span class=\"logo\">\n",
      "        MARS Planet Science\n",
      "       </span>\n",
      "       <span class=\"logo1\">\n",
      "        Exploration Program\n",
      "       </span>\n",
      "      </a>\n",
      "      <button aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" class=\"navbar-toggler\" data-bs-target=\"#navbarNav\" data-bs-toggle=\"collapse\" type=\"button\">\n",
      "       <span class=\"navbar-toggler-icon\">\n",
      "       </span>\n",
      "      </button>\n",
      "      <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarNav\">\n",
      "       <ul class=\"navbar-nav\">\n",
      "        <li class=\"nav-item\">\n",
      "         <a aria-current=\"page\" class=\"nav-link active\" href=\"#\">\n",
      "          The Red Planet\n",
      "         </a>\n",
      "        </li>\n",
      "        <li class=\"nav-item\">\n",
      "         <a class=\"nav-link\" href=\"#\">\n",
      "          The Program\n",
      "         </a>\n",
      "        </li>\n",
      "        <li class=\"nav-item\">\n",
      "         <a class=\"nav-link\" href=\"#\">\n",
      "          News &amp; Events\n",
      "         </a>\n",
      "        </li>\n",
      "        <li class=\"nav-item\">\n",
      "         <a class=\"nav-link\" href=\"#\">\n",
      "          Multimedia\n",
      "         </a>\n",
      "        </li>\n",
      "        <li class=\"nav-item\">\n",
      "         <a class=\"nav-link\" href=\"#\">\n",
      "          Missions\n",
      "         </a>\n",
      "        </li>\n",
      "        <li class=\"nav-item\">\n",
      "         <a class=\"nav-link\" href=\"#\">\n",
      "          More\n",
      "         </a>\n",
      "        </li>\n",
      "        <li class=\"nav-item nav_search\">\n",
      "         <a class=\"nav-link\" href=\"#\">\n",
      "         </a>\n",
      "        </li>\n",
      "       </ul>\n",
      "      </div>\n",
      "     </div>\n",
      "    </nav>\n",
      "    <section class=\"search\">\n",
      "     <div class=\"container\">\n",
      "      <h1>\n",
      "       News\n",
      "      </h1>\n",
      "      <div class=\"col-md-12 filter\">\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-3 search_binder\">\n",
      "         <input class=\"search_field\" name=\"search\" type=\"text\"/>\n",
      "         <input class=\"search_submit\" name=\"search\" type=\"text\"/>\n",
      "        </div>\n",
      "        <div class=\"col-md-3\">\n",
      "         <select aria-label=\"Default select example\" class=\"form-select\" id=\"year\">\n",
      "          <option selected=\"\">\n",
      "           Latest\n",
      "          </option>\n",
      "          <option>\n",
      "           2020\n",
      "          </option>\n",
      "          <option>\n",
      "           2019\n",
      "          </option>\n",
      "         </select>\n",
      "        </div>\n",
      "        <div class=\"col-md-3\">\n",
      "         <select aria-label=\"Default select example\" class=\"form-select\" id=\"cat\">\n",
      "          <option selected=\"\">\n",
      "           All Categories\n",
      "          </option>\n",
      "          <option>\n",
      "           Feature Stories\n",
      "          </option>\n",
      "          <option>\n",
      "           Press Releases\n",
      "          </option>\n",
      "          <option>\n",
      "           Status Reports\n",
      "          </option>\n",
      "         </select>\n",
      "        </div>\n",
      "        <div class=\"col-md-3\">\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "     </div>\n",
      "    </section>\n",
      "    <section class=\"image_and_description_container\">\n",
      "     <div class=\"container\" id=\"news\">\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8611_PIA22111-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           September 6, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA Adds Return Sample Scientists to Mars 2020 Leadership Team\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           The leadership council for Mars 2020 science added two new members who represent the interests of scientists destined to handle and study the first samples from Red Planet.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8666_PIA23776-main-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           September 5, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA Perseverance Mars Rover Scientists Train in the Nevada Desert\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           Team members searched for signs of ancient microscopic life there, just as NASA's latest rover will on the Red Planet next year.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8712_PIA23720-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           September 4, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           6 Things to Know About NASA's Ingenuity Mars Helicopter\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           The first helicopter attempting to fly on another planet is a marvel of engineering. Get up to speed with these key facts about its plans.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8785_PIA24231-320.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           September 4, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA's Perseverance Rover Is Midway to Mars\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           Sometimes half measures can be a good thing – especially on a journey this long. The agency's latest rover only has about 146 million miles left to reach its destination.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8663_PIA23316-annotated-16-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           September 4, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA's Perseverance Rover Will Look at Mars Through These 'Eyes'\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           A pair of zoomable cameras will help scientists and rover drivers with high-resolution color images.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8641_PIA-23821-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 30, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA's Perseverance Mars Rover Gets Its Wheels and Air Brakes\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           After the rover was shipped from JPL to Kennedy Space Center, the team is getting closer to finalizing the spacecraft for launch later this summer.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8537_PIA23468-16_320x240px.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 28, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           Mars 2020 Stands on Its Own Six Wheels\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           In time-lapse video, taken at JPL, captures the first time NASA's Mars 2020 rover carries its full weight on its legs and wheels.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8596_mavenatmars-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 27, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA's MAVEN Explores Mars to Understand Radio Interference at Earth\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           NASA’s MAVEN spacecraft has discovered “layers” and “rifts” in the electrically charged part of the upper atmosphere of Mars.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8585_name20190625-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 27, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA's Mars 2020 Rover Closer to Getting Its Name\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           155 students from across the U.S. have been chosen as semifinalists in NASA's essay contest to name the Mars 2020 rover, and see it launch from Cape Canaveral this July.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8408_22206_PIA22655-th.gif\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 25, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           The MarCO Mission Comes to an End\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           The pair of briefcase-sized satellites made history when they sailed past Mars in 2019.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8798_PIA22109-320.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 21, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           Mars Is Getting a New Robotic Meteorologist\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           Sensors on NASA's Perseverance will help prepare for future human exploration by taking weather measurements and studying dust particles.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8797_maven_illo_v7-320.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 20, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           Heat and Dust Help Launch Martian Water Into Space, Scientists Find\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           Scientists using an instrument aboard NASA’s Mars Atmosphere and Volatile EvolutioN, or MAVEN, spacecraft have discovered that water vapor near the surface of the Red Planet is lofted higher into the atmosphere than anyone expected was possible.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8603_list_image.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 18, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           NASA Administrator Statement on Moon to Mars Initiative, FY 2021 Budget\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           Jim Bridenstine addresses NASA's ambitious plans for the coming years, including Mars Sample Return.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8613_InSight-Nature-papers-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 13, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           A Year of Surprising Science From NASA's InSight Mars Mission\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           A batch of new papers summarizes the lander's findings above and below the surface of the Red Planet.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "      <div class=\"col-md-12\">\n",
      "       <hr/>\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-4\">\n",
      "         <div class=\"list_image\">\n",
      "          <img src=\"https://mars.nasa.gov/system/news_items/list_view_images/8678_21379_PIA22107-320x240.jpg\"/>\n",
      "         </div>\n",
      "        </div>\n",
      "        <div class=\"col-md-8\">\n",
      "         <div class=\"list_text\">\n",
      "          <div class=\"list_date\">\n",
      "           August 8, 2021\n",
      "          </div>\n",
      "          <div class=\"content_title\">\n",
      "           The Detective Aboard NASA's Perseverance Rover\n",
      "          </div>\n",
      "          <div class=\"article_teaser_body\">\n",
      "           An instrument called SHERLOC will, with the help of its partner WATSON, hunt for signs of ancient life by detecting organic molecules and minerals.\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "     </div>\n",
      "     <hr class=\"container\" style=\"margin: 25px auto;width: 83%;\"/>\n",
      "     <button class=\"btn disable\" id=\"more\" onclick=\"populateContent()\">\n",
      "      More\n",
      "     </button>\n",
      "    </section>\n",
      "    <section class=\"last_news\">\n",
      "     <div class=\"container\">\n",
      "      <div class=\"row\">\n",
      "       <div class=\"col-12\">\n",
      "        <h2>\n",
      "         You Might Also Like\n",
      "        </h2>\n",
      "       </div>\n",
      "       <!--  <a class=\" prev\" href=\"#carouselExampleIndicators2\" role=\"button\" data-slide=\"prev\">\n",
      "                  <i class=\"fas fa-angle-left\"></i>\n",
      "                  </a>\n",
      "                  <a class=\" next\" href=\"#carouselExampleIndicators2\" role=\"button\" data-slide=\"next\">\n",
      "                  <i class=\"fas fa-angle-right\"></i>\n",
      "                  </a> -->\n",
      "       <div class=\"col-12\">\n",
      "        <div class=\"carousel slide\" data-ride=\"carousel\" id=\"carouselExampleIndicators2\">\n",
      "         <div class=\"carousel-inner\">\n",
      "          <div class=\"carousel-item active\">\n",
      "           <div class=\"row\">\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://mars.nasa.gov/system/news_items/main_images/8716_PIA23499-16.jpg\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                NASA to Broadcast Mars 2020 Perseverance Launch, Prelaunch Activities\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://mars.nasa.gov/system/news_items/main_images/8716_PIA23499-16.jpg\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                The Launch Is Approaching for NASA's Next Mars Rover, Perseverance\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://mars.nasa.gov/system/news_items/main_images/8692_PIA23920-web.jpg\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                NASA to Hold Mars 2020 Perseverance Rover Launch Briefing\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "           </div>\n",
      "          </div>\n",
      "          <div class=\"carousel-item\">\n",
      "           <div class=\"row\">\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://images.unsplash.com/photo-1532771098148-525cefe10c23?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=3f317c1f7a16116dec454fbc267dd8e4\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                With supporting text below as a natural lead-in to additional content.\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://images.unsplash.com/photo-1532715088550-62f09305f765?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=ebadb044b374504ef8e81bdec4d0e840\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                With supporting text below as a natural lead-in to additional content.\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=0754ab085804ae8a3b562548e6b4aa2e\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                With supporting text below as a natural lead-in to additional content.\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "           </div>\n",
      "          </div>\n",
      "          <div class=\"carousel-item\">\n",
      "           <div class=\"row\">\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=ee8417f0ea2a50d53a12665820b54e23\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                With supporting text below as a natural lead-in to additional content.\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://images.unsplash.com/photo-1532777946373-b6783242f211?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=8ac55cf3a68785643998730839663129\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                With supporting text below as a natural lead-in to additional content.\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "            <div class=\"col-md-4 mb-3\">\n",
      "             <div class=\"card\">\n",
      "              <img alt=\"100%x280\" class=\"img-fluid\" src=\"https://images.unsplash.com/photo-1532763303805-529d595877c5?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1080&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=5ee4fd5d19b40f93eadb21871757eda6\"/>\n",
      "              <div class=\"card-body\">\n",
      "               <p class=\"card-text\">\n",
      "                With supporting text below as a natural lead-in to additional content.\n",
      "               </p>\n",
      "              </div>\n",
      "             </div>\n",
      "            </div>\n",
      "           </div>\n",
      "          </div>\n",
      "         </div>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "     </div>\n",
      "    </section>\n",
      "    <section class=\"footer\">\n",
      "     <div class=\"container\">\n",
      "      <div class=\"col-md-12\">\n",
      "       <div class=\"row\">\n",
      "        <div class=\"col-md-3\">\n",
      "         <h5>\n",
      "          The Red Planet\n",
      "         </h5>\n",
      "         <ul>\n",
      "          <li>\n",
      "           Dashboard\n",
      "          </li>\n",
      "          <li>\n",
      "           Science Goals\n",
      "          </li>\n",
      "          <li>\n",
      "           The Planet\n",
      "          </li>\n",
      "         </ul>\n",
      "        </div>\n",
      "        <div class=\"col-md-3\">\n",
      "         <h5>\n",
      "          The Program\n",
      "         </h5>\n",
      "         <ul>\n",
      "          <li>\n",
      "           Mission Statement\n",
      "          </li>\n",
      "          <li>\n",
      "           About the Program\n",
      "          </li>\n",
      "          <li>\n",
      "           Organization Why Mars?\n",
      "          </li>\n",
      "         </ul>\n",
      "        </div>\n",
      "        <div class=\"col-md-3\">\n",
      "         <h5>\n",
      "          Multimedia\n",
      "         </h5>\n",
      "         <ul>\n",
      "          <li>\n",
      "           Images\n",
      "          </li>\n",
      "          <li>\n",
      "           Videos\n",
      "          </li>\n",
      "          <li>\n",
      "           More Resources\n",
      "          </li>\n",
      "         </ul>\n",
      "        </div>\n",
      "        <div class=\"col-md-3\">\n",
      "         <h5>\n",
      "          Missions\n",
      "         </h5>\n",
      "         <ul>\n",
      "          <li>\n",
      "           Past\n",
      "          </li>\n",
      "          <li>\n",
      "           Present\n",
      "          </li>\n",
      "          <li>\n",
      "           Future\n",
      "          </li>\n",
      "         </ul>\n",
      "        </div>\n",
      "       </div>\n",
      "      </div>\n",
      "     </div>\n",
      "    </section>\n",
      "    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\" type=\"text/javascript\">\n",
      "    </script>\n",
      "    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\">\n",
      "    </script>\n",
      "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js\">\n",
      "    </script>\n",
      "    <script src=\"js/app.js\">\n",
      "    </script>\n",
      "   </div>\n",
      "  </div>\n",
      " </body>\n",
      "</html>\n"
     ]
    }
   ],
   "source": [
    "# Use BeautifulSoup to help find and parse out the necessary data.  Use either html.parser or lxml parser.\n",
    "# Create a Beautiful Soup object\n",
    "soup_mars_news = bs(html_mars_news, 'html.parser')\n",
    "\n",
    "# Print formatted version of the soup\n",
    "print(soup_mars_news.prettify())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "news_title = \"NASA Adds Return Sample Scientists to Mars 2020 Leadership Team\"\n",
      "news_p = \"The leadership council for Mars 2020 science added two new members who represent the interests of scientists destined to handle and study the first samples from Red Planet.\"\n",
      "********************\n",
      "news_title = \"NASA Perseverance Mars Rover Scientists Train in the Nevada Desert\"\n",
      "news_p = \"Team members searched for signs of ancient microscopic life there, just as NASA's latest rover will on the Red Planet next year.\"\n",
      "********************\n",
      "news_title = \"6 Things to Know About NASA's Ingenuity Mars Helicopter\"\n",
      "news_p = \"The first helicopter attempting to fly on another planet is a marvel of engineering. Get up to speed with these key facts about its plans.\"\n",
      "********************\n",
      "news_title = \"NASA's Perseverance Rover Is Midway to Mars \"\n",
      "news_p = \"Sometimes half measures can be a good thing – especially on a journey this long. The agency's latest rover only has about 146 million miles left to reach its destination.\"\n",
      "********************\n",
      "news_title = \"NASA's Perseverance Rover Will Look at Mars Through These 'Eyes'\"\n",
      "news_p = \"A pair of zoomable cameras will help scientists and rover drivers with high-resolution color images.\"\n",
      "********************\n",
      "news_title = \"NASA's Perseverance Mars Rover Gets Its Wheels and Air Brakes\"\n",
      "news_p = \"After the rover was shipped from JPL to Kennedy Space Center, the team is getting closer to finalizing the spacecraft for launch later this summer.\"\n",
      "********************\n",
      "news_title = \"Mars 2020 Stands on Its Own Six Wheels\"\n",
      "news_p = \"In time-lapse video, taken at JPL, captures the first time NASA's Mars 2020 rover carries its full weight on its legs and wheels.\"\n",
      "********************\n",
      "news_title = \"NASA's MAVEN Explores Mars to Understand Radio Interference at Earth\"\n",
      "news_p = \"NASA’s MAVEN spacecraft has discovered “layers” and “rifts” in the electrically charged part of the upper atmosphere of Mars.\"\n",
      "********************\n",
      "news_title = \"NASA's Mars 2020 Rover Closer to Getting Its Name\"\n",
      "news_p = \"155 students from across the U.S. have been chosen as semifinalists in NASA's essay contest to name the Mars 2020 rover, and see it launch from Cape Canaveral this July.\"\n",
      "********************\n",
      "news_title = \"The MarCO Mission Comes to an End\"\n",
      "news_p = \"The pair of briefcase-sized satellites made history when they sailed past Mars in 2019.\"\n",
      "********************\n",
      "news_title = \"Mars Is Getting a New Robotic Meteorologist\"\n",
      "news_p = \"Sensors on NASA's Perseverance will help prepare for future human exploration by taking weather measurements and studying dust particles.\"\n",
      "********************\n",
      "news_title = \"Heat and Dust Help Launch Martian Water Into Space, Scientists Find\"\n",
      "news_p = \"Scientists using an instrument aboard NASA’s Mars Atmosphere and Volatile EvolutioN, or MAVEN, spacecraft have discovered that water vapor near the surface of the Red Planet is lofted higher into the atmosphere than anyone expected was possible. \"\n",
      "********************\n",
      "news_title = \"NASA Administrator Statement on Moon to Mars Initiative, FY 2021 Budget\"\n",
      "news_p = \"Jim Bridenstine addresses NASA's ambitious plans for the coming years, including Mars Sample Return.\"\n",
      "********************\n",
      "news_title = \"A Year of Surprising Science From NASA's InSight Mars Mission\"\n",
      "news_p = \"A batch of new papers summarizes the lander's findings above and below the surface of the Red Planet.\"\n",
      "********************\n",
      "news_title = \"The Detective Aboard NASA's Perseverance Rover\"\n",
      "news_p = \"An instrument called SHERLOC will, with the help of its partner WATSON, hunt for signs of ancient life by detecting organic molecules and minerals.\"\n",
      "********************\n"
     ]
    }
   ],
   "source": [
    "# Collect the latest News Title and Paragraph Text.\n",
    "list_text_list = soup_mars_news.find_all('div', class_='list_text')\n",
    "\n",
    "content_title_strip_list = []\n",
    "article_teaser_body_strip_list = []\n",
    "\n",
    "# Loop through returned results (from 12-2-04)\n",
    "for result in list_text_list:\n",
    "    \n",
    "    # Retrieve the title\n",
    "    content_title = result.find('div', class_='content_title')\n",
    "    content_title_strip = content_title.text.lstrip()\n",
    "    print(f'news_title = \"' + content_title_strip + '\"')\n",
    "    content_title_strip_list.append(content_title_strip)\n",
    "    \n",
    "    # Retrieve the article body\n",
    "    article_teaser_body = result.find('div', class_='article_teaser_body')\n",
    "    article_teaser_body_strip = article_teaser_body.text.lstrip()\n",
    "    print(f'news_p = \"' + article_teaser_body_strip + '\"')\n",
    "    article_teaser_body_strip_list.append(article_teaser_body_strip)\n",
    "    print ('********************')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### JPL Mars Space Images - Featured Image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visit the url for the Featured Space Image site [here](https://spaceimages-mars.com).\n",
    "url_mars_imag = 'https://spaceimages-mars.com'\n",
    "browser.visit(url_mars_imag)\n",
    "html_mars_imag = browser.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Use BeautifulSoup to help find and parse out the necessary data.  Use either html.parser or lxml parser.\n",
    "# Create a Beautiful Soup object\n",
    "soup_mars_imag = bs(html_mars_imag, 'html.parser')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://spaceimages-mars.com/image/featured/mars3.jpg\n"
     ]
    }
   ],
   "source": [
    "# Use splinter to navigate the site and find the image url for the current Featured Mars Image and assign the url \n",
    "    # string to a variable called `featured_image_url`.  Make sure to find the image url to the full size `.jpg` image.\n",
    "    # reference C:\\Users\\jjel0\\OneDrive\\class_repo\\gt-virt-atl-data-pt-06-2021-u-c-2\\12-Web-Scraping-and-Document-Databases\\2\\Activities\\07-Ins_Splinter\n",
    "    # Example:\n",
    "        # featured_image_url = 'https://spaceimages-mars.com/image/featured/mars2.jpg'\n",
    "\n",
    "        # Collect the latest News Title and Paragraph Text.\n",
    "featured_image = soup_mars_imag.find('a', class_='showimg fancybox-thumbs')\n",
    "href = featured_image['href']\n",
    "featured_image_url = 'https://spaceimages-mars.com/' + href\n",
    "print(featured_image_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<a class=\"showimg fancybox-thumbs\" href=\"image/featured/mars3.jpg\" target=\"_blank\"> <button class=\"btn btn-outline-light\"> FULL IMAGE</button></a>"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "featured_image"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Mars Facts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visit the Mars Facts webpage [here](https://galaxyfacts-mars.com) and use Pandas to scrape the table containing\n",
    "    # facts about the planet including Diameter, Mass, etc.\n",
    "url_mars_facts = 'https://galaxyfacts-mars.com'\n",
    "browser.visit(url_mars_facts)\n",
    "html_mars_facts = browser.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a Beautiful Soup object\n",
    "soup_mars_facts = bs(html_mars_facts, 'lxml')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[                         0                1                2\n",
       " 0  Mars - Earth Comparison             Mars            Earth\n",
       " 1                Diameter:         6,779 km        12,742 km\n",
       " 2                    Mass:  6.39 × 10^23 kg  5.97 × 10^24 kg\n",
       " 3                   Moons:                2                1\n",
       " 4       Distance from Sun:   227,943,824 km   149,598,262 km\n",
       " 5          Length of Year:   687 Earth days      365.24 days\n",
       " 6             Temperature:     -87 to -5 °C      -88 to 58°C,\n",
       "                       0                              1\n",
       " 0  Equatorial Diameter:                       6,792 km\n",
       " 1       Polar Diameter:                       6,752 km\n",
       " 2                 Mass:  6.39 × 10^23 kg (0.11 Earths)\n",
       " 3                Moons:          2 ( Phobos & Deimos )\n",
       " 4       Orbit Distance:       227,943,824 km (1.38 AU)\n",
       " 5         Orbit Period:           687 days (1.9 years)\n",
       " 6  Surface Temperature:                   -87 to -5 °C\n",
       " 7         First Record:              2nd millennium BC\n",
       " 8          Recorded By:           Egyptian astronomers]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Use Pandas to convert the data to a HTML table string.\n",
    "html_mars_facts_df = pd.read_html(url_mars_facts)\n",
    "html_mars_facts_df"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Mars Hemispheres"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visit the astrogeology site [here](https://marshemispheres.com/) to obtain high resolution images for each of \n",
    "    # Mars hemispheres.\n",
    "url_mars_hemis = 'https://marshemispheres.com/'\n",
    "browser.visit(url_mars_hemis)\n",
    "html_mars_hemis = browser.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<a class=\"itemLink product-item\" href=\"cerberus.html\"><img alt=\"Cerberus Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/39d3266553462198bd2fbc4d18fbed17_cerberus_enhanced.tif_thumb.png\"/></a>,\n",
       " <a class=\"itemLink product-item\" href=\"cerberus.html\">\n",
       " <h3>Cerberus Hemisphere Enhanced</h3>\n",
       " </a>,\n",
       " <a class=\"itemLink product-item\" href=\"schiaparelli.html\"><img alt=\"Schiaparelli Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/08eac6e22c07fb1fe72223a79252de20_schiaparelli_enhanced.tif_thumb.png\"/></a>,\n",
       " <a class=\"itemLink product-item\" href=\"schiaparelli.html\">\n",
       " <h3>Schiaparelli Hemisphere Enhanced</h3>\n",
       " </a>,\n",
       " <a class=\"itemLink product-item\" href=\"syrtis.html\"><img alt=\"Syrtis Major Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/55a0a1e2796313fdeafb17c35925e8ac_syrtis_major_enhanced.tif_thumb.png\"/></a>,\n",
       " <a class=\"itemLink product-item\" href=\"syrtis.html\">\n",
       " <h3>Syrtis Major Hemisphere Enhanced</h3>\n",
       " </a>,\n",
       " <a class=\"itemLink product-item\" href=\"valles.html\"><img alt=\"Valles Marineris Hemisphere Enhanced thumbnail\" class=\"thumb\" src=\"images/4e59980c1c57f89c680c0e1ccabbeff1_valles_marineris_enhanced.tif_thumb.png\"/></a>,\n",
       " <a class=\"itemLink product-item\" href=\"valles.html\">\n",
       " <h3>Valles Marineris Hemisphere Enhanced</h3>\n",
       " </a>,\n",
       " <a class=\"itemLink product-item\" href=\"#\" onclick=\"showMain()\">\n",
       " <h3>Back</h3>\n",
       " </a>]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Use BeautifulSoup to help find and parse out the necessary data.  Use either html.parser or lxml parser.\n",
    "# Create a Beautiful Soup object\n",
    "soup_mars_hemis = bs(html_mars_hemis, 'html.parser')\n",
    "\n",
    "# Print the image links\n",
    "hemis_url_list = soup_mars_hemis.find_all('a', class_='itemLink product-item')\n",
    "hemis_url_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['https://marshemispheres.com/cerberus.html',\n",
       " 'https://marshemispheres.com/cerberus.html',\n",
       " 'https://marshemispheres.com/schiaparelli.html',\n",
       " 'https://marshemispheres.com/schiaparelli.html',\n",
       " 'https://marshemispheres.com/syrtis.html',\n",
       " 'https://marshemispheres.com/syrtis.html',\n",
       " 'https://marshemispheres.com/valles.html',\n",
       " 'https://marshemispheres.com/valles.html',\n",
       " 'https://marshemispheres.com/#']"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "content_title_hemis_list = []\n",
    "hemis_image_url_list = []\n",
    "# Loop through returned results\n",
    "for result in hemis_url_list:\n",
    "    \n",
    "    # Retrieve the title\n",
    "    content_title = result.find('h3')\n",
    "    content_title_hemis_list.append(content_title)\n",
    "    \n",
    "    # Retrieve the images of the hemisphers\n",
    "    hemis_image = soup_mars_hemis.find('a', class_='itemLink product-item')\n",
    "    href = result['href']\n",
    "    hemis_image_url = 'https://marshemispheres.com/' + href\n",
    "#     print(hemis_image_url)\n",
    "    hemis_image_url_list.append(hemis_image_url)\n",
    "\n",
    "Not_none_values = filter(None.__ne__, content_title_hemis_list)\n",
    "\n",
    "content_title_hemis_listvalues = list(Not_none_values)\n",
    "\n",
    "hemis_image_url_list\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "# You will need to click each of the links to the hemispheres in order to find the image url to the full\n",
    "    # resolution image.\n",
    "# Save both the image url string for the full resolution hemisphere image, and the Hemisphere title containing\n",
    "    # the hemisphere name. Use a Python dictionary to store the data using the keys `img_url` and `title`.\n",
    "\n",
    "\n",
    "# Append the dictionary with the image url string and the hemisphere title to a list. This list will contain\n",
    "    # one dictionary for each hemisphere.\n",
    "hemisphere_image_urls = [\n",
    "    {\"title\": \"Valles Marineris Hemisphere\", \"img_url\": \"https://marshemispheres.com/images/valles_marineris_enhanced-full.jpg\"},\n",
    "    {\"title\": \"Cerberus Hemisphere\", \"img_url\": \"https://marshemispheres.com/images/valles_marineris_enhanced-full.jpg\"},\n",
    "    {\"title\": \"Schiaparelli Hemisphere\", \"img_url\": \"https://marshemispheres.com/images/schiaparelli_enhanced-full.jpg\"},\n",
    "    {\"title\": \"Syrtis Major Hemisphere\", \"img_url\": \"https://marshemispheres.com/images/syrtis_major_enhanced-full.jpg\"},\n",
    "]\n"
   ]
  },
#   {
#    "cell_type": "code",
#    "execution_count": null,
#    "metadata": {},
#    "outputs": [],
#    "source": []
#   }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
